version: "3"
services:
    rabbitmq:
        image: rabbitmq:3.8.22-management
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - 5672:5672
            - 15672:15672
